"""initial schema

Revision ID: 597f1fda2b3c
Revises: 
Create Date: 2026-07-01 08:52:41.099855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597f1fda2b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=150), nullable=False),
    sa.Column('dept_head', sa.String(length=100), nullable=True),
    sa.Column('annual_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=200), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('credit_hrs', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('students',
    sa.Column('stu_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=80), nullable=False),
    sa.Column('lname', sa.String(length=80), nullable=False),
    sa.Column('email_addr', sa.String(length=120), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('join_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ),
    sa.PrimaryKeyConstraint('stu_id'),
    sa.UniqueConstraint('email_addr')
    )
    op.create_table('enrollments',
    sa.Column('enroll_id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=False),
    sa.Column('grade_val', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['students.stu_id'], ),
    sa.PrimaryKeyConstraint('enroll_id'),
    sa.UniqueConstraint('stu_id', 'course_id', name='uq_stu_course')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('students')
    op.drop_table('courses')
    op.drop_table('departments')
    # ### end Alembic commands ###
