"""add is_active to students

Revision ID: 88fc3a0c476d
Revises: 78908e854b00
Create Date: 2026-06-23 22:45:55.188334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88fc3a0c476d'
down_revision: Union[str, Sequence[str], None] = '78908e854b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('students', 'student_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('email'), table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'students', ['email'], unique=True)
    op.alter_column('students', 'student_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
